version: '3.8'
services:
   travel-app:
      build:
         context: .
         dockerfile: Dockerfile
      ports:
         - '3000:3000'
      volumes:
         - ./app:/app/app
      environment:
         - CHOKIDAR_USEPOLLING=true
